version: "3.9"
services:
  fastapi:
    build: .
    container_name: upocket-api
    ports:
      - "8000:8000"
    develop:
          watch:
            - action: sync+restart
              path: ./app
              target: /app/app
    