services:
  fastapi:
    build: .
    container_name: upocket-api
    ports:
      - "8002:8000"
    restart: unless-stopped
    develop:
          watch:
            - action: sync+restart
              path: ./app
              target: /app/app
